### ISSUE TITLE
[SUGGESTION] It is not clear if, or how, to disable default controller names

### ISSUE THREAD

**Issue by raoulkent** [oas-tools/oas-tools.github.io#3]
In the documentation [Default controller names](https://oas-tools.github.io/docs/features/routing#default-controller-names) it says:
> By default, when there are no attributes in the OpenAPI document that specify controller or operation names, OAS Tools generates a name for them:

This does however not specify how one can disable this default, or if possible.

**Describe the solution you'd like**
I think it would be clearer if it were explicitly stated if this is possible or not. And if it is possible, say how one can do so.

**Comment by alesancor1** [comment]
Controller and operation default names are overridden by `x-router-controller` and `operationId` fields in the OpenAPI document. Maybe rewritting it the following way makes it more clear:

> When there are no attributes in the OpenAPI document that specify user defined names for controllers or operations, OAS Tools generates a name for them

I think that "By default" makes it confusing since it seems like a togglable option when it actually is a name that is set when no user defined name is specified.

**Comment by raoulkent** [comment]
Absolutely. I think that makes it much clearer. I made the mistake of believing it was togglable.

Your edit makes it clear that it has one of two possible behaviours.
